name: iOS CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: setup-cocoapods
        uses: maxim-lobanov/setup-cocoapods@v1
        with:
          podfile-path: ios/Podfile.lock
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.5.2
        with:
          node-version: '16'
          cache: npm
          cache-dependency-path: '**/package-lock.json'
        
      - run: npm install
        
      - run: npm install -g appcenter-cli

      - run: fastlane ios publishDevelopmentFromGithubActions
        env:
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          GITHUB_ACCESSKEY_FASTLANE_MATCH: ${{ secrets.ACCESSKEY_FASTLANE_MATCH }}
          FASTLANE_APPCENTER_IOS_API_TOKEN: ${{ secrets.APPCENTER_DEV_IOS_API_TOKEN }}

